# Generated by Django 6.0.2 on 2026-02-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Rezerwacja', 'verbose_name_plural': 'Rezerwacje'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Wyposażenie', 'verbose_name_plural': 'Wyposażenie'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Powiadomienie', 'verbose_name_plural': 'Powiadomienia'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Sala', 'verbose_name_plural': 'Sale'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Użytkownik', 'verbose_name_plural': 'Użytkownicy'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', '✓ Potwierdzona'), ('pending', '⏳ Oczekująca'), ('cancelled', '✗ Anulowana'), ('completed', '✔ Zakończona')], default='confirmed', max_length=20),
        ),
    ]
