# Generated by Django 6.0.2 on 2026-02-15 12:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_options_alter_equipment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(verbose_name='Pojemność'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Piętro'),
        ),
        migrations.AlterField(
            model_name='room',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Stawka godzinowa'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Status (Aktywna)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nazwa sali'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data dołączenia'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Departament'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Adres e-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Administrator'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Imię i nazwisko'),
        ),
    ]
